name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: |
        npm run lint
        npm run type-check

    - name: Build extension
      run: npm run build

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create extension package
      run: |
        cd dist
        zip -r ../e-ink-reader-extension-${{ steps.get_version.outputs.VERSION }}.zip .
        cd ..
        echo "📦 Extension package created: e-ink-reader-extension-${{ steps.get_version.outputs.VERSION }}.zip"
        echo "Package contents:"
        unzip -l e-ink-reader-extension-${{ steps.get_version.outputs.VERSION }}.zip

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        body: |
          ## E-Ink Reader Extension ${{ steps.get_version.outputs.VERSION }}
          
          ### Installation
          1. Download the `e-ink-reader-extension-${{ steps.get_version.outputs.VERSION }}.zip` file
          2. Extract the ZIP file
          3. Open Chrome and go to `chrome://extensions/`
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
          
          ### Changes
          See the commit history for detailed changes in this release.

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./e-ink-reader-extension-${{ steps.get_version.outputs.VERSION }}.zip
        asset_name: e-ink-reader-extension-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip